# Generated by Django 5.2.8 on 2025-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reviwed', 'Reviewed')], default='requested', max_length=20),
        ),
    ]
